avatar.scan.url=https://avatarscan.hpi.com

#Avatar Config

avatar.content.length.limit=5000


http.conn.timeout=30000
http.proxy.enabled=false
http.proxy.host=web-proxy.cup.hp.com
http.proxy.port=8080
http.max.conn.per.route=10
http.max.total.conn=30
http.socket.timeout=30000


avatar.tunnel.config.api.url=http://localhost:9194/cms/v1/entities/{cloud_id}/tunnel_config/{signal_type}
avatar.set.signal.api.url=http://localhost:9194/cms/v1/entities/signal/{cloud_id}


avatar.tunnel.config.failure.retry.attempt=3
avatar.tunnel.config.failure.retry.sleep.duration=5000
avatar.sigmgmtclient.disable.hostname.verification=true
avatar.sigmgmtclient.avatar.set.signal.api.version=1.0
avatar.set.signal.auth.header=test1